src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message = "Merci de remplir le titre !")
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message = "Merci d'indiquer le nombre de pages !")
     */
    private $nbPages;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\NotBlank(message = "Merci d'entrer un résumé !")
     */
    private $resume;

    /**
     * @ORM\ManyToOne(targetEntity=Genre::class, inversedBy="books")
     * @ORM\JoinColumn(nullable=false)
     */
    private $genre;

    /**
     * @ORM\OneToMany(targetEntity=Author::class, mappedBy="book")
     */
    private $authors;

    /**
     * @ORM\ManyToOne(targetEntity=author::class, inversedBy="books")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $book_cover;

    /*
    public function __construct()
    {
        $this->authors = new ArrayCollection();
    }
     */

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getNbPages(): ?int
    {
        return $this->nbPages;
    }

    public function setNbPages(int $nbPages): self
    {
        $this->nbPages = $nbPages;

        return $this;
    }


    /**
     * @param mixed $resume
     */
    public function setResume($resume): void
    {
        $this->resume = $resume;
    }

    /**
     * @return mixed
     */
    public function getResume()
    {
        return $this->resume;
    }

    public function getGenre(): ?genre
    {
        return $this->genre;
    }

    public function setGenre(?genre $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    /**
     * @return Collection|Author[]
     */
    public function getAuthors(): Collection
    {
        return $this->authors;
    }

    public function addAuthor(Author $author): self
    {
        if (!$this->authors->contains($author)) {
            $this->authors[] = $author;
            $author->setBook($this);
        }

        return $this;
    }

    public function removeAuthor(Author $author): self
    {
        if ($this->authors->contains($author)) {
            $this->authors->removeElement($author);
            // set the owning side to null (unless already changed)
            if ($author->getBook() === $this) {
                $author->setBook(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?author
    {
        return $this->author;
    }

    public function setAuthor(?author $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getBookCover(): ?string
    {
        return $this->book_cover;
    }

    public function setBookCover(string $book_cover): self
    {
        $this->book_cover = $book_cover;

        return $this;
    }

}

templates/accueil.html.twig
{% extends 'base.html.twig' %}
{% block content %}
    <div class="block">

    <div class="barre">
        <ul class="genresList">

            {% for genre in genres %}
                <a href={{ path('booksGenre', {'name':genre.name})}}  >{{ genre.name }}</a>
            {% endfor %}

        </ul>
    </div>

    <div class="content">
        <div class="accueil">
            <h2>Bienvenu sur la bibliothèque</h2>
            <div class="prez">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, eaque, omnis. Adipisci corporis culpa ducimus ex, illum incidunt nesciunt nihil optio possimus quasi quibusdam, quidem tempora temporibus vel, voluptatem voluptatum.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid assumenda error et itaque labore necessitatibus obcaecati, quidem quis? Accusantium aliquid amet at laboriosam libero placeat quaerat quasi quidem quos ullam!
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ab, animi assumenda corporis cum dolorum eos eveniet hic id illo ipsa maxime minus nemo nesciunt nobis provident ratione saepe voluptas.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis delectus dolorem ducimus harum id, libero praesentium quis reprehenderit! Aliquam dolorum, error impedit inventore libero nulla qui quidem reiciendis repellendus voluptatum?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium alias aut deleniti deserunt eveniet ex maxime pariatur quaerat, quibusdam quis repellendus similique tempora voluptas. Delectus dicta ex incidunt obcaecati porro?
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores aspernatur cupiditate dicta error, ex, ipsum minima minus molestiae nemo neque nostrum odit officiis porro rem repellat, repudiandae totam vel voluptatem!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, assumenda beatae, delectus deserunt distinctio dolore eaque eos eum explicabo fugit inventore ipsam neque nostrum nulla porro sapiente tempore ut veritatis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut dicta doloribus eveniet fuga odit quae quaerat quibusdam unde! Accusamus aperiam autem deserunt, dolorum illum iste laudantium molestias placeat temporibus totam.</p>
            </div>
        </div>

        <div class="last_authors">
            <h3>les derniers auteurs</h3>
            <div class="last_author">

                {% for author in authors %}
                    <div class="authors">

                        <a href="{{ path('author_show', {'id':author.id}) }}">

                            <!--le nom/prenom de l'auteur de l'auteur-->
                            <h2>{{ author.firstname }} {{ author.lastname }}</h2>

                            <!--la biographie de l'auteur-->
                            <p>{{ author.biography }}</p>

                            <!--afficher la date de naissance / mort de l'auteur-->
                            {% if author.deathdate==null %}
                                <p>{{ author.birthdate|date('d-M-Y') }}</p>
                            {% else %}
                                <p>{{ author.birthdate|date('d-M-Y') }} / {{ author.deathdate|date('d-M-Y') }}</p>
                            {% endif %}
                        </a>

                    </div>
                {% endfor %}

            </div>
        </div>
        <div class="last_books">
            <h3>Les derniers livres</h3>
            <div class="last_book">

                {% for book in books %}

                    <div class="books">
                        <a href="{{ path('book_show', {'id':book.id}) }}">
                            <!--le titre du livre-->
                            <h2>{{ book.title }}</h2>
                            <!--l'image du livre-->
                            <div class="picture">
                                <img src="{{ asset('uploads/book/'~book.bookCover) }}" alt="" class="adminBook_img">
                            </div>
                            <!--les info du livre-->
                            <p>type : {{ book.genre.name }} - {{ book.nbPages }} pages</p>
                        </a>
                    </div>

                {% endfor %}

            </div>
        </div>
    </div>

{% endblock %}

templates/author.html.twig
{% extends 'base.html.twig' %}
{% block content %}

    <div class="content">
        <div class="author">
            <!--le nom/prenom de l'auteur de l'auteur-->
                <h2>{{ author.firstname }} {{ author.lastname }}</h2>

            <!--la biographie de l'auteur-->
                <p>{{ author.biography }}</p>

            <!--afficher la date de naissance / mort de l'auteur-->
                    {% if author.deathdate==null %}
                        <p>{{ author.birthdate|date('d-M-Y') }}</p>
                    {% else %}
                        <p>{{ author.birthdate|date('d-M-Y') }} / {{ author.deathdate|date('d-M-Y') }}</p>
                    {% endif %}
        </div>

{% endblock content %}

templates/base.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ asset('style.css') }}">
    <title>Document</title>

</head>
<body>

<!--le header-->
<header>
    <h1>Sombre Librairie</h1>
    <!--la barre de navigation-->
    <ul class="nav_barre">
        <li><a href="{{ path('accueil') }}">l'accueil</a></li>
        <li><a href="{{ path('authors_list') }}">les auteurs</a></li>
        <li><a href="{{ path('books_list') }}">les livres</a></li>
        <li><a href="{{ path('search_result') }}">recherche</a></li>
        <li><a href="{{ path('admin_accueil') }}">se connecter</a></li>
    </ul>
</header>

<!--le contenu-->
<div class="main">
    {% block content %}

    {% endblock content%}
</div>

<!--le footer-->
<footer>

</footer>
</body>
</html>

templates/book.html.twig
{% extends 'base.html.twig' %}
{% block content %}

        <div class="content">
                <div class="book">
                        <!--le titre du livre-->
                        <h2>{{ book.title }}</h2>
                        <!--l'image du livre-->
                        <div class="picture">
                                <img src="{{ asset('uploads/book/'~book.bookCover) }}" alt="" class="adminBook_img">
                        </div>
                        <!--les info du livre-->
                        <p>type : {{ book.genre.name }} - {{ book.nbPages }} pages</p>
                </div>
        </div>

{% endblock content %}

templates/books.html.twig
{% extends 'base.html.twig' %}
{% block content %}

    <div class="content">
        <!--la boucle qui fera apparaitre les livres sur la page-->
        {% for book in books %}

            <div class="books">
                <a href="{{ path('book_show', {'id':book.id}) }}">
                    <!--le titre du livre-->
                        <h2>{{ book.title }}</h2>
                    <!--l'image du livre-->
                    <div class="picture">
                        <img src="{{ asset('uploads/book/'~book.bookCover) }}" alt="" class="adminBook_img">
                    </div>
                    <!--les info du livre-->
                    <p>type : {{ book.genre.name }} - {{ book.nbPages }} pages</p>
                </a>
            </div>

        {% endfor %}
    </div>

{% endblock content %}

templates/inscription.html.twig
{% extends 'base.html.twig' %}
{% block content %}

    <h3>Inscription</h3>

    <div class="formUser">
        {{ form(userForm) }}
    </div>

{% endblock content %}

templates/newBook.html.twig
{% extends 'base.html.twig' %}
{% block content %}

    <div class="blocFormAjout">
        <form action="" method="" class="formAjout">
            <label for="">entrez le titre : </label>
            <input type="text" name="title" id="title">
            <label for="">entrez le résumé :</label>
            <input type="text" name="resume" id="resume" class="resume">
            <label for="">entrez le genre :</label>
            <input type="text" name="genre" id="genre">
            <label for="">entrez le nombre de pages :</label>
            <input type="text" name="nmbPages" id="nmbPages">
            <input type="button" value="Envoyer" class="boutton">
        </form>
    </div>

{% endblock %}

templates/search.html.twig
{% extends 'base.html.twig' %}
{% block content %}

    <div class="content_search">

        <div class="form_search">
            <form action="" method="get">
                <label for="">rechercher : </label>
                <input name="search" type="text">
            </form>
        </div>

        <div class="result">
            {% for book in books%}
                <div class="book">
                    <!--le titre du livre-->
                    <h2>{{ book.title }}</h2>
                    <!--l'image du livre-->
                    <div class="picture">
                        <img src="{{ asset('uploads/book/'~book.bookCover) }}" alt="" class="adminBook_img">
                    </div>
                    <!--le résumé du livre-->
                    <p>{{ book.resume }}</p>
                    <!--les info du livre-->
                    <p>type : {{ book.genre.name }} - {{ book.nbPages }} pages</p>
                </div>
            {% endfor %}
            {% if (books ==null) %}
                <div class="empty">
                    <p>Entrez une requete s'il vous plait</p>
                </div>
            {% endif %}
        </div>

    </div>

{% endblock %}